language: node_js
node_js:
  - "stable"
addons:
  chrome: stable
sudo: false

after_script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then npm run lh -- --perf=96 --pwa=100 --a11y 88 --bp 85 https://deploy-preview-"$TRAVIS_PULL_REQUEST"--zen-euclid-6d318e.netlify.com; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then npm run lh -- --perf=96 --pwa=100 --a11y 88 --bp 85 https://ossn.club; fi'
